Proto
shipherman/speech-to-text pull request #2
Opened 2023-12-18 09:20 UTC by shipherman

Основной функционал реализован, осталось добавить храние результатов в ОЗУ, очередь, worker pool и graceful shutdown на стороне сервера. Постараюсь до вечера сделать, и потом добавлю тесты

2024-01-21 19:24 UTC, avhitrov requested changes
1. Причесать возвращение ошибок и использование Fatal в рабочих процессах
2. Причесать логирование, избавиться от fmt.PrintX.
3. Избавиться от production-секретов в коде репозитория.
4. Прочие придирки в комментариях.

2024-01-21 19:24 UTC, avhitrov commented on internal/handlers/handle-stt.go
> +		log.Fatalf("failed opening connection to postgres: %v", err)
Хендлер вебсервера, способный обвалить вебсервер в случае потери или отказе в соединении с БД, не имеет права на существование.

Не очень понятно, почему соединение открывается при каждом обращении к хендлеру. Учитывая то, что на количество одновременных соединений с базой всегда ставится какое-то ограничение, становится возможным уронить сервер, просто открыв одновременно к нему 200..300+ запросов. 

Обычной практикой является установка одного соединения на один экземпляр сервера на все время работы.

2024-04-02 19:38 UTC, shipherman commented on cmd/client/cmd/auth.go
> +	uri ...string) (map[string]string, error) {
tokenAuth должен удовлетворять интерфейсу PerRPCCredentials, поэтому добавил входные аргументы

2024-04-17 23:14 UTC, avhitrov requested changes
Отличная работа! Осталось одно замечание относительно порядка остановки сервисов при шатдауне и вопрос о реализации отображения истории в клиенте.

2024-04-17 23:14 UTC, avhitrov commented on cmd/server/cmd/root.go
> +	grpcServer.GracefulStop()
```suggestion
	grpcServer.GracefulStop()
	transcribeServer.Store.Close()
	transcribeServer.DBClient.Close()
```
Сначала следует погасить grpc-сервер, чтобы он более не принимал соединений и не пытался писать в сторадж. Потом погасить сторадж и только после этого закрыть соединение с БД. Иначе есть большой риск словить на шатдауне панику.

2024-04-17 23:14 UTC, avhitrov commented on cmd/client/cmd/history.go
> +		// Show the result
Будет реализовано в пределах данного ПР или потом? Если в другом ПР, то я просто закрою этот комментарий.

2024-04-18 15:04 UTC, shipherman commented on cmd/client/cmd/history.go
> +		// Show the result
Добавил получение истории запросов

2024-04-19 22:37 UTC, avhitrov approved these changes
Замечания исправлены, более косяков не заметил. Аппрув!

2024-04-21 09:18 UTC, merged